name: Deploy mdBook to higher-kinded-j.github.io

on:
  push:
    branches:
      - main
    paths:
      - 'hkj-book/**'
      - '.github/workflows/deploy-mdbook.yml'
  workflow_dispatch:
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout 'higher-kinded-j' repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable # Installs Rust and Cargo
        with:
          toolchain: stable

      - name: Install mdbook-sitemap-generator ( किल्ला version )
        run: cargo install mdbook-sitemap-generator

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.4.48'

      - name: Build mdBook (with sitemap preprocessor)
        working-directory: ./hkj-book
        run: mdbook build

      - name: Deploy to higher-kinded-j.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          external_repository: higher-kinded-j/higher-kinded-j.github.io
          publish_branch: main
          publish_dir: ./hkj-book/book
          keep_files: false
          force_orphan: true
          commit_message: 'docs: Deploy latest mdBook documentation from higher-kinded-j repository'
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

