name: Deploy mdBook to higher-kinded-j.github.io

on:
  push:
    branches:
      - main
    paths:
      - 'hkj-book/**'
      - '.github/workflows/deploy-mdbook.yml'
  workflow_dispatch:
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout 'higher-kinded-j' repository
        uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.4.48'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Copy root files to book source
        run: |
          BOOK_SRC_DIR="hkj-book/src" # Define variable for clarity
          mkdir -p "$BOOK_SRC_DIR"         # Ensure directory exists
          echo "Copying root files to $BOOK_SRC_DIR"
          cp CONTRIBUTING.md "$BOOK_SRC_DIR/"
          cp LICENSE.md "$BOOK_SRC_DIR/"
          cp CODE_OF_CONDUCT.md "$BOOK_SRC_DIR/"
          # Add other files here if needed, copying them INTO the $BOOK_SRC_DIR
          echo "Files copied:"
          ls -l "$BOOK_SRC_DIR" # List files for verification in logs


      - name: Build mdBook
        working-directory: ./hkj-book
        run: mdbook build

      - name: Generate Sitemap
        run: python .github/scripts/generate_sitemap.py
        env:
          MDBOOK_OUTPUT_DIR: ./hkj-book/book
          MDBOOK_SITE_URL: "https://higher-kinded-j.github.io/"

      - name: Deploy to higher-kinded-j/higher-kinded-j.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          external_repository: higher-kinded-j/higher-kinded-j.github.io
          publish_branch: main
          publish_dir: ./hkj-book/book
          keep_files: false
          force_orphan: true
          commit_message: 'docs: Deploy latest mdBook documentation from higher-kinded-j repository'
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

