name: Deploy mdBook to higher-kinded-j.github.io

on:
  push:
    branches:
      - main
    paths:
      - 'hkj-book/**'
      - '.github/workflows/deploy-mdbook.yml'
  workflow_dispatch:
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout 'higher-kinded-j' repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain (trying older version for sitemap generator)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: '1.67.0' # Rust version from early 2023, when v0.2.0 was released

      - name: Configure Cargo and Git for CI
        run: |
          mkdir -p $HOME/.cargo
          echo -e "\n[net]\ngit-fetch-with-cli = true\n" >> $HOME/.cargo/config.toml
          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global credential.helper ""

      - name: Install mdbook-sitemap-generator ( किल्ला/mdbook-sitemap-generator )
        # This installs v0.2.0 from crates.io
        run: cargo install mdbook-sitemap-generator --version 0.2.0 --locked

      - name: Setup mdBook (using a specific version might also help consistency)
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.4.21' # Example: A version of mdbook also from around that time or latest

#      - name: Setup mdBook
#        uses: peaceiris/actions-mdbook@v2
#        with:
#          mdbook-version: 'latest' # 0.4.49

      - name: Build mdBook (with sitemap preprocessor)
        working-directory: ./hkj-book
        run: mdbook build

      - name: Deploy to higher-kinded-j.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          external_repository: higher-kinded-j/higher-kinded-j.github.io
          publish_branch: main
          publish_dir: ./hkj-book/book
          keep_files: false
          force_orphan: true
          commit_message: 'docs: Deploy latest mdBook documentation from higher-kinded-j repository'
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

