name: Publish Higher-Kinded-J package to GitHub Packages

on:
  push:
    tags: # Trigger publishing only when a tag is pushed (e.g., 'v1.0.0')
      - 'v*' # Matches tags like v1.0, v2.3.4 etc.
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Optional: Validate Gradle wrapper checksum for security
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Extract tag version
        id: tag_version # Give this step an ID to reference its output
        # Check if the ref is a tag before trying to extract
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # github.ref is 'refs/tags/v1.2.0', we want '1.2.0' (remove 'refs/tags/v')
          # If your tags don't have 'v', just remove 'refs/tags/'
          TAG_NAME="${{ github.ref }}"
          VERSION=${TAG_NAME#refs/tags/v}
          # If tag didn't have 'v' prefix, VERSION would still be the tag name
          # If you *only* want tags without 'v', adjust the script or the 'on:' trigger
          echo "Tag version extracted: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT" # Set output variable for the step


      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish package to GitHub Packages
        run: ./gradlew publish
        env:
          # GITHUB_ACTOR is automatically provided by GitHub Actions
          # GITHUB_TOKEN is automatically provided when permissions.packages: write is set
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}